/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import daycare.anak;
import daycare.koneksibos;
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author KH
 */
public class filteranak extends javax.swing.JFrame {

    /**
     * Creates new form filteranak
     */
    PreparedStatement pst;
    Connection con;
    ResultSet rs;
    public filteranak() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
//    String driver = "com.microsoft.sqlserver.jdbc.SQLServerDriver";
//    String url ="jdbc:sqlserver://CHEETAH;databaseName=zendaycare";
//    String user ="sa";
//    String pass = "123qwe";
//    
//      String driver = "com.mysql.jdbc.Driver";
//
//      String url = "jdbc:mysql://localhost:3306/zendaycare";
//      String user = "root";
//      String pass = "";
      
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txt_auto3 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        txtnama1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(85, 170, 228));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pict/close1.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel10MousePressed(evt);
            }
        });
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, -1, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel4.setText("DATA ANAK");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 60));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setText("ID ORANG TUA");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, 30));

        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextField1.setText("PLEASE VERIFY YOUR ID");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 160, 30));

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setText("VERIFY");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 80, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_anak", "Nama_lengkap", "TTL", "jenis kelamin", "id orang tua"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 420, 100));

        txt_auto3.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        txt_auto3.setText("AUTO");
        getContentPane().add(txt_auto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 142, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel3.setText("User:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Tempat, Tanggal Lahir");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Nama lengkap");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("Jenis kelamin");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, -1, -1));

        jDateChooser1.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, 210, 30));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("ID Anak");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, 30));

        jTextField2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextField2.setText("PLEASE VERIFY YOUR ID");
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 160, 30));

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setText("DELETE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 520, 80, 40));

        txtnama1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtnama1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        getContentPane().add(txtnama1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 210, 30));

        jLabel1.setText("AUTO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 460, -1, -1));

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setText("VERIFY");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 80, 30));

        jButton4.setBackground(new java.awt.Color(204, 204, 204));
        jButton4.setText("UPDATE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 520, 80, 40));

        setSize(new java.awt.Dimension(533, 594));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
       
      public void refresh()
      {
        
        jTextField1.setText("PLEASE VERIFY YOUR ID");
        jTextField2.setText("PLEASE VERIFY YOUR ID");        
        txtnama1.setText(null);
        jLabel1.setText("AUTO");
       
      }
    
    // UNTUK MEMANGGIL DATA DARI DATABASE UNTUK VIEW DATA DI JTABLE
    public ArrayList<anak> List1(String valtosearch)
    {
        ArrayList<anak> List1 = new ArrayList<>();
        try
        {
            con = new koneksibos().setConnection();
            String query1= "select * from anak where CONCAT(Nama_lengkap, id_orangtua)like '%" + valtosearch + "%' ";               
            Statement st = con.createStatement();
            rs = st.executeQuery(query1);
            anak conn;
            while(rs.next()){
                conn = new anak(rs.getString("id_anak"),rs.getString("Nama_lengkap"),rs.getString("TTL"),rs.getString("jenis_kelamin"), rs.getString("id_orangtua"));
                List1.add(conn);
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
            System.out.println("error");
        }
        return List1;
    }
    
    public void showdata1()
    {
        ArrayList<anak> list1 = List1(jTextField1.getText());
        
        DefaultTableModel model = new DefaultTableModel();
        //model.setRowCount(0);
        model.setColumnIdentifiers(new Object[]{"id_anak","Nama_lengkap","TTL,","jenis kelamin", "id orang tua"});
        Object[] row = new Object[5];
        for(int i = 0;i<list1.size();i++)
        {        
            row[0] = list1.get(i).callIDa();
            row[1] = list1.get(i).callnama();
            row[2] = list1.get(i).callTtl();
            row[3] = list1.get(i).calljenkel();
            row[4] = list1.get(i).callIDo();
            model.addRow(row);
        }
        jTable1.setModel(model);
        
    
    }
    
    public void Search()
    {    
        try            
        {
                         
            
           con = new koneksibos().setConnection();
            
            String sql ="select * from anak where id_anak=?";   
            pst = con.prepareStatement(sql);
            pst.setString(1, jTextField2.getText());
            
            rs = pst.executeQuery();
            if(rs.next())
            {
                JOptionPane.showMessageDialog(this, " Data yang anda masukkan valid"); 
                String namaanak= rs.getString("Nama_lengkap");
                txtnama1.setText(namaanak);
           
                String DOF = rs.getString("TTL");
                SimpleDateFormat f = new SimpleDateFormat("yyyy-MM-dd");
                java.util.Date d = f.parse(DOF);   
                jDateChooser1.setDate(d);
                
                String  JenKel = rs.getString("jenis_kelamin");
                jLabel1.setText(JenKel);
                
            }
            else
            {
                JOptionPane.showMessageDialog(this, " Data yang anda masukkan tidak valid");            
            }                    
        }
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(filteranak.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void UPDATE()
    {
        try
        {
            //declare variabel 
            String nama = txtnama1.getText();
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String dates = sdf.format(jDateChooser1.getDate());
           
              //connection with database 
            con = new koneksibos().setConnection();
            String sql="update anak set Nama_lengkap=?, TTL=? ";
            //validation rule        
        
            pst = con.prepareStatement(sql);
            pst.setString(1, nama);
            pst.setString(2, dates);

            // SINTAK FOR SAVE TO DATABASE
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, " Data Have been Inserted Successfull");
              refresh();
            // IdAuto();
             
             // back to menu login
            anakP x = new anakP();
            anakP.txt_auto.setText(TambahAnak.txt_auto2.getText());
            x.setVisible(true);
            hide();
        }
        catch(HeadlessException | SQLException e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
            JOptionPane.showMessageDialog(this, "ada yang error mungkin, coba periksa lagi dengan benar ya" );
        }
    }
 
      public void delete()
      {
        try
        {
            String sql="delete FROM anak where id_anak=?";
            pst = con.prepareStatement(sql);
            pst.setString(1, jTextField2.getText());
          
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, " Data has been Deleted Successfull");
            refresh();
        }
        catch(HeadlessException | SQLException e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }      
    
    public void setcolor(JPanel pane)
    {
        pane.setBackground(new Color(32, 67, 102));
        
    }    

    public void resetcolor(JPanel[] pane, JPanel [] indicators)
    {
        for (int i=0; i<pane.length; i++)
        {
            pane[i].setBackground(new Color(0, 40, 80));
        }
        for(int i=0;i<indicators.length;i++)
        {
           indicators[i].setOpaque(false);           
        }
        
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        showdata1();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MousePressed
        anakP xx = new anakP();
        anakP.txt_auto.setText(TambahAnak.txt_auto2.getText());
        xx.setVisible(true);
        hide();
    }//GEN-LAST:event_jLabel10MousePressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add
        delete();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        UPDATE();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(filteranak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(filteranak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(filteranak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(filteranak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new filteranak().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    public static javax.swing.JLabel txt_auto3;
    private javax.swing.JTextField txtnama1;
    // End of variables declaration//GEN-END:variables
}
