/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;


import daycare.bayar;
import daycare.jenjangs;
import daycare.koneksibos;
import daycare.paket;
import daycare.regis1;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author KH
 */
public class MainPegawai extends javax.swing.JFrame {
Connection con;
    /**
     * Creates new form MainPegawai
     */
    public MainPegawai() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidePane = new javax.swing.JPanel();
        btn_Home = new javax.swing.JPanel();
        ind1 = new javax.swing.JPanel();
        lbl8 = new javax.swing.JLabel();
        btn_anak = new javax.swing.JPanel();
        ind2 = new javax.swing.JPanel();
        lbl9 = new javax.swing.JLabel();
        btn_transaksi = new javax.swing.JPanel();
        ind3 = new javax.swing.JPanel();
        lbl10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidePane.setBackground(new java.awt.Color(0, 40, 80));
        sidePane.setForeground(new java.awt.Color(255, 255, 255));
        sidePane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        sidePane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Home.setBackground(new java.awt.Color(0, 40, 80));
        btn_Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_HomeMousePressed(evt);
            }
        });

        ind1.setOpaque(false);
        ind1.setPreferredSize(new java.awt.Dimension(5, 43));

        javax.swing.GroupLayout ind1Layout = new javax.swing.GroupLayout(ind1);
        ind1.setLayout(ind1Layout);
        ind1Layout.setHorizontalGroup(
            ind1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        ind1Layout.setVerticalGroup(
            ind1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        lbl8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl8.setForeground(new java.awt.Color(255, 255, 255));
        lbl8.setText("Home");

        javax.swing.GroupLayout btn_HomeLayout = new javax.swing.GroupLayout(btn_Home);
        btn_Home.setLayout(btn_HomeLayout);
        btn_HomeLayout.setHorizontalGroup(
            btn_HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_HomeLayout.createSequentialGroup()
                .addComponent(ind1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 105, Short.MAX_VALUE))
            .addGroup(btn_HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btn_HomeLayout.createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addComponent(lbl8, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(39, Short.MAX_VALUE)))
        );
        btn_HomeLayout.setVerticalGroup(
            btn_HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ind1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(btn_HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btn_HomeLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lbl8, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        sidePane.add(btn_Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, -1, -1));

        btn_anak.setBackground(new java.awt.Color(0, 40, 80));
        btn_anak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_anakMousePressed(evt);
            }
        });

        ind2.setOpaque(false);
        ind2.setPreferredSize(new java.awt.Dimension(5, 43));

        javax.swing.GroupLayout ind2Layout = new javax.swing.GroupLayout(ind2);
        ind2.setLayout(ind2Layout);
        ind2Layout.setHorizontalGroup(
            ind2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        ind2Layout.setVerticalGroup(
            ind2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        lbl9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl9.setForeground(new java.awt.Color(255, 255, 255));
        lbl9.setText("Registrasi");

        javax.swing.GroupLayout btn_anakLayout = new javax.swing.GroupLayout(btn_anak);
        btn_anak.setLayout(btn_anakLayout);
        btn_anakLayout.setHorizontalGroup(
            btn_anakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_anakLayout.createSequentialGroup()
                .addComponent(ind2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 105, Short.MAX_VALUE))
            .addGroup(btn_anakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btn_anakLayout.createSequentialGroup()
                    .addGap(24, 24, 24)
                    .addComponent(lbl9)
                    .addContainerGap(28, Short.MAX_VALUE)))
        );
        btn_anakLayout.setVerticalGroup(
            btn_anakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ind2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(btn_anakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btn_anakLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lbl9, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        sidePane.add(btn_anak, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, -1, -1));

        btn_transaksi.setBackground(new java.awt.Color(0, 40, 80));
        btn_transaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_transaksiMousePressed(evt);
            }
        });

        ind3.setOpaque(false);
        ind3.setPreferredSize(new java.awt.Dimension(5, 43));

        javax.swing.GroupLayout ind3Layout = new javax.swing.GroupLayout(ind3);
        ind3.setLayout(ind3Layout);
        ind3Layout.setHorizontalGroup(
            ind3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        ind3Layout.setVerticalGroup(
            ind3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        lbl10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl10.setForeground(new java.awt.Color(255, 255, 255));
        lbl10.setText("Pembayaran");

        javax.swing.GroupLayout btn_transaksiLayout = new javax.swing.GroupLayout(btn_transaksi);
        btn_transaksi.setLayout(btn_transaksiLayout);
        btn_transaksiLayout.setHorizontalGroup(
            btn_transaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_transaksiLayout.createSequentialGroup()
                .addComponent(ind3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 105, Short.MAX_VALUE))
            .addGroup(btn_transaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btn_transaksiLayout.createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addComponent(lbl10, javax.swing.GroupLayout.PREFERRED_SIZE, 77, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        btn_transaksiLayout.setVerticalGroup(
            btn_transaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ind3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(btn_transaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btn_transaksiLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lbl10, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        sidePane.add(btn_transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 110, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pict/mothers1.png"))); // NOI18N
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel13MousePressed(evt);
            }
        });
        sidePane.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pict/exit.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel11MousePressed(evt);
            }
        });
        sidePane.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        getContentPane().add(sidePane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 550));

        jPanel2.setBackground(new java.awt.Color(85, 170, 228));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("REFRESH");
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 70, -1, 40));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("REFRESH");
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 70, -1, 40));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("REFRESH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, 100, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 820, 30));

        jScrollPane2.setOpaque(false);

        jTable2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "no registrasi", "tgl registrasi", "jam registrasi", "id anak", "id orangtua", "id service", "id jenjang", "harga layanan", "status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setOpaque(false);
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 770, 110));

        jScrollPane3.setOpaque(false);

        jTable3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "no pembayaran", "tanggal pembayaran", "jam pembayaran", "no registrasi", "total pembayaran", "status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable3.setOpaque(false);
        jScrollPane3.setViewportView(jTable3);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 770, 100));

        jScrollPane4.setOpaque(false);

        jTable4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id jenjang", "nama jenjang", "usia"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable4.setOpaque(false);
        jScrollPane4.setViewportView(jTable4);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, 320, 110));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("REGISTRASI");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(319, 319, 319)
                .addComponent(jLabel4)
                .addContainerGap(350, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 130, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 790, 160));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("PEMBAYARAN");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(306, 306, 306)
                .addComponent(jLabel5)
                .addContainerGap(343, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 130, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 790, -1));

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("JENJANG");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(121, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 130, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 350, -1));

        jScrollPane5.setOpaque(false);

        jTable5.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id layanan", "nama layanan", "harga"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable5.setOpaque(false);
        jScrollPane5.setViewportView(jTable5);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 430, 300, 110));

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("LAYANAN");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 130, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 390, 330, -1));

        setSize(new java.awt.Dimension(945, 590));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

        //arraylist  for layanan
    public ArrayList<paket> List1(){

        ArrayList<paket> List1 = new ArrayList<>();
        try
        {
         con = new koneksibos().setConnection();
            String query1= "select * from layanan ";               
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query1);
            
            paket conn;
            while(rs.next()){
                conn = new paket(rs.getString("id_service"),rs.getString("nama_service"),rs.getString("harga"));
                List1.add(conn);
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
            System.out.println("error");
        }
        return List1;
    }
    
     public ArrayList<jenjangs> List2()
     {
        ArrayList<jenjangs> List2 = new ArrayList<>();
        try
        {
            con = new koneksibos().setConnection();
            String query1= "select * from jenjang ";               
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query1);
            jenjangs conn;
            while(rs.next()){
                conn = new jenjangs(rs.getString("id_jenjang"),rs.getString("Nama_jenjang"),rs.getString("usia"));
                List2.add(conn);
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
            System.out.println("error");
        }
        return List2;
    }
     
     public ArrayList<bayar> List3()
     {
        ArrayList<bayar> List3 = new ArrayList<>();
        try
        {
           con = new koneksibos().setConnection();
            String query1= "select * from pembayaran ";               
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query1);
            bayar conn;
            while(rs.next()){
                conn = new bayar(rs.getString("no_pembayaran"),rs.getString("tanggal_pembayaran"), rs.getString("jam_pembayaran") ,rs.getString("no_registrasi"),rs.getString("total_pemabayaran"), rs.getString("statuss"));
                List3.add(conn);
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
            System.out.println("error");
        }
        return List3;
    }     
     
     public ArrayList<regis1> List4()
     {

        ArrayList<regis1> List4 = new ArrayList<>();
        try
        {
            con = new koneksibos().setConnection();
            String query1= "select * from registrasi ";               
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query1);
            regis1 conn;
            
            while(rs.next())
            {
                conn = new regis1(rs.getString("no_registrasi"), rs.getString("tanggal_registrasi"), rs.getString("jam_registrasi") , rs.getString("id_anak"), rs.getString("id_orangtua"), rs.getString("id_jenjang"), rs.getString("id_service"), rs.getString("harga_layanan"), rs.getString("statuss"));
                
                List4.add(conn);
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
            System.out.println("error");
        }
        return List4;
    } 
    //show data grid layanan
    public void showdata()
    {
        ArrayList<paket> list1 = List1();
        DefaultTableModel model = (DefaultTableModel)jTable5.getModel();
        model.setRowCount(0);
        
        Object[] row = new Object[3];
        for(int i = 0;i<list1.size();i++)
        {        
            row[0] = list1.get(i).callID();
            row[1] = list1.get(i).callnama();
            row[2] = list1.get(i).callharga();
            
            model.addRow(row);
        }
    
    }
    //show data grid jenjang

    public void showdata1()
    {
        ArrayList<jenjangs> list2 = List2();
        DefaultTableModel model = (DefaultTableModel)jTable4.getModel();
        model.setRowCount(0);
        
        Object[] row = new Object[3];
        for(int i = 0;i<list2.size();i++)
        {        
            row[0] = list2.get(i).callID();
            row[1] = list2.get(i).callnama();
            row[2] = list2.get(i).callusia();
            
            model.addRow(row);
        }
    
    }
        //show data grid pembayaran
    public void showdata2()
    {
        ArrayList<bayar> list3 = List3();
        DefaultTableModel model = (DefaultTableModel)jTable3.getModel();
        model.setRowCount(0);
        
        Object[] row = new Object[6];
        for(int i = 0;i<list3.size();i++)
        {        
            row[0] = list3.get(i).callID();
            row[1] = list3.get(i).calltanggal();            
            row[2] = list3.get(i).calljam();
            row[3] = list3.get(i).callnoreg();
            row[4] = list3.get(i).calldenda();
            row[5] = list3.get(i).callstat();
            
            
            model.addRow(row);
        }    
    }    
    
      public void showdata3()
    {
        ArrayList<regis1> list4 = List4();
        DefaultTableModel model = (DefaultTableModel)jTable2.getModel();
        model.setRowCount(0);
        
        Object[] row = new Object[9];
        for(int i = 0;i<list4.size();i++)
        {        
            row[0] = list4.get(i).callNo();
            row[1] = list4.get(i).calltangreg();
            row[2] = list4.get(i).calljamreg();            
            row[3] = list4.get(i).callanak();
            row[4] = list4.get(i).callIDortu();
            row[5] = list4.get(i).calljenjang();
            row[6] = list4.get(i).callservice();
            row[7] = list4.get(i).callharga();
            row[8] = list4.get(i).callstatus();
            
            model.addRow(row);
        }    
    }    
        // aksesoris
    public void setcolor(JPanel pane)
    {
        pane.setBackground(new Color(32, 67, 102));
        
    }
   
    public void resetcolor(JPanel[] pane, JPanel [] indicators)
    {
    for (JPanel pane1 : pane) {
        pane1.setBackground(new Color(0, 40, 80));
    }
    for (JPanel indicator : indicators) {
        indicator.setOpaque(false);
    }
        
    }
    private void btn_HomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_HomeMousePressed
        // TODO add your handling code here:
        setcolor(btn_Home);
        ind1.setOpaque(true);
        resetcolor(new JPanel[]{btn_anak,btn_transaksi}, new JPanel[]{ind2,ind3});

    }//GEN-LAST:event_btn_HomeMousePressed

    private void btn_anakMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_anakMousePressed
        // TODO add your handling code here:
        setcolor(btn_anak);
        ind2.setOpaque(true);
        resetcolor(new JPanel[]{btn_Home,btn_transaksi}, new JPanel[]{ind1,ind3});
        regisEm reg = new regisEm();
        reg.show();
        hide();
    }//GEN-LAST:event_btn_anakMousePressed

    private void btn_transaksiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_transaksiMousePressed
        // TODO add your handling code here:
        setcolor(btn_transaksi);
        ind3.setOpaque(true);
        resetcolor(new JPanel[]{btn_Home,btn_anak}, new JPanel[]{ind2,ind1});
        
        pembayaran bayar = new pembayaran();
        bayar.show();
        hide();
    }//GEN-LAST:event_btn_transaksiMousePressed

    private void jLabel13MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel13MousePressed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        showdata();
        showdata1();
        showdata2();
        showdata3();
    }//GEN-LAST:event_formWindowActivated

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        showdata();
        showdata1();
        showdata2();
        showdata3();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel11MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MousePressed
        // TODO add your handling code here:
        logins pergi = new logins();
        pergi.show();
        hide();
    }//GEN-LAST:event_jLabel11MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPegawai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btn_Home;
    private javax.swing.JPanel btn_anak;
    private javax.swing.JPanel btn_transaksi;
    private javax.swing.JPanel ind1;
    private javax.swing.JPanel ind2;
    private javax.swing.JPanel ind3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JLabel lbl10;
    private javax.swing.JLabel lbl8;
    private javax.swing.JLabel lbl9;
    private javax.swing.JPanel sidePane;
    // End of variables declaration//GEN-END:variables
}
