/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;
import daycare.*;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import daycare.koneksibos;

/**
 *
 * @author KH
 */
public class MainParent extends javax.swing.JFrame {

    /**
     * Creates new form MainParent
     */
    public MainParent() 
    {
        initComponents();
       
    }
Connection con;
    public MainParent(String para)
    {
        initComponents();
       // txt_auto.setText(para);
      
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidePane = new javax.swing.JPanel();
        btn_Home = new javax.swing.JPanel();
        ind1 = new javax.swing.JPanel();
        lbl8 = new javax.swing.JLabel();
        btn_anak = new javax.swing.JPanel();
        ind2 = new javax.swing.JPanel();
        lbl9 = new javax.swing.JLabel();
        btn_transaksi = new javax.swing.JPanel();
        ind3 = new javax.swing.JPanel();
        lbl10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btn_setting = new javax.swing.JPanel();
        ind4 = new javax.swing.JPanel();
        lbl11 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txt_auto = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cnthome = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setName("MP"); // NOI18N
        setUndecorated(true);
        setType(java.awt.Window.Type.UTILITY);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidePane.setBackground(new java.awt.Color(0, 40, 80));
        sidePane.setForeground(new java.awt.Color(255, 255, 255));
        sidePane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        sidePane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Home.setBackground(new java.awt.Color(0, 40, 80));
        btn_Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_HomeMousePressed(evt);
            }
        });

        ind1.setOpaque(false);
        ind1.setPreferredSize(new java.awt.Dimension(5, 43));

        javax.swing.GroupLayout ind1Layout = new javax.swing.GroupLayout(ind1);
        ind1.setLayout(ind1Layout);
        ind1Layout.setHorizontalGroup(
            ind1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        ind1Layout.setVerticalGroup(
            ind1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        lbl8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl8.setForeground(new java.awt.Color(255, 255, 255));
        lbl8.setText("Home");

        javax.swing.GroupLayout btn_HomeLayout = new javax.swing.GroupLayout(btn_Home);
        btn_Home.setLayout(btn_HomeLayout);
        btn_HomeLayout.setHorizontalGroup(
            btn_HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_HomeLayout.createSequentialGroup()
                .addComponent(ind1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 105, Short.MAX_VALUE))
            .addGroup(btn_HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btn_HomeLayout.createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addComponent(lbl8, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(39, Short.MAX_VALUE)))
        );
        btn_HomeLayout.setVerticalGroup(
            btn_HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ind1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(btn_HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btn_HomeLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lbl8, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        sidePane.add(btn_Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, -1, -1));

        btn_anak.setBackground(new java.awt.Color(0, 40, 80));
        btn_anak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_anakMousePressed(evt);
            }
        });

        ind2.setOpaque(false);
        ind2.setPreferredSize(new java.awt.Dimension(5, 43));

        javax.swing.GroupLayout ind2Layout = new javax.swing.GroupLayout(ind2);
        ind2.setLayout(ind2Layout);
        ind2Layout.setHorizontalGroup(
            ind2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        ind2Layout.setVerticalGroup(
            ind2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        lbl9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl9.setForeground(new java.awt.Color(255, 255, 255));
        lbl9.setText("Anak");

        javax.swing.GroupLayout btn_anakLayout = new javax.swing.GroupLayout(btn_anak);
        btn_anak.setLayout(btn_anakLayout);
        btn_anakLayout.setHorizontalGroup(
            btn_anakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_anakLayout.createSequentialGroup()
                .addComponent(ind2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 105, Short.MAX_VALUE))
            .addGroup(btn_anakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btn_anakLayout.createSequentialGroup()
                    .addGap(24, 24, 24)
                    .addComponent(lbl9, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(45, Short.MAX_VALUE)))
        );
        btn_anakLayout.setVerticalGroup(
            btn_anakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ind2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(btn_anakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btn_anakLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lbl9, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        sidePane.add(btn_anak, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, -1, -1));

        btn_transaksi.setBackground(new java.awt.Color(0, 40, 80));
        btn_transaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_transaksiMousePressed(evt);
            }
        });

        ind3.setOpaque(false);
        ind3.setPreferredSize(new java.awt.Dimension(5, 43));

        javax.swing.GroupLayout ind3Layout = new javax.swing.GroupLayout(ind3);
        ind3.setLayout(ind3Layout);
        ind3Layout.setHorizontalGroup(
            ind3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        ind3Layout.setVerticalGroup(
            ind3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        lbl10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl10.setForeground(new java.awt.Color(255, 255, 255));
        lbl10.setText("Transaksi");

        javax.swing.GroupLayout btn_transaksiLayout = new javax.swing.GroupLayout(btn_transaksi);
        btn_transaksi.setLayout(btn_transaksiLayout);
        btn_transaksiLayout.setHorizontalGroup(
            btn_transaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_transaksiLayout.createSequentialGroup()
                .addComponent(ind3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 105, Short.MAX_VALUE))
            .addGroup(btn_transaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btn_transaksiLayout.createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addComponent(lbl10, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(24, Short.MAX_VALUE)))
        );
        btn_transaksiLayout.setVerticalGroup(
            btn_transaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ind3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(btn_transaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btn_transaksiLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lbl10, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        sidePane.add(btn_transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 110, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pict/mothers1.png"))); // NOI18N
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel13MousePressed(evt);
            }
        });
        sidePane.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        btn_setting.setBackground(new java.awt.Color(0, 40, 80));
        btn_setting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_settingMousePressed(evt);
            }
        });

        ind4.setOpaque(false);
        ind4.setPreferredSize(new java.awt.Dimension(5, 43));

        javax.swing.GroupLayout ind4Layout = new javax.swing.GroupLayout(ind4);
        ind4.setLayout(ind4Layout);
        ind4Layout.setHorizontalGroup(
            ind4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        ind4Layout.setVerticalGroup(
            ind4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        lbl11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl11.setForeground(new java.awt.Color(255, 255, 255));
        lbl11.setText("Setting");

        javax.swing.GroupLayout btn_settingLayout = new javax.swing.GroupLayout(btn_setting);
        btn_setting.setLayout(btn_settingLayout);
        btn_settingLayout.setHorizontalGroup(
            btn_settingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_settingLayout.createSequentialGroup()
                .addComponent(ind4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 105, Short.MAX_VALUE))
            .addGroup(btn_settingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btn_settingLayout.createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addComponent(lbl11, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(24, Short.MAX_VALUE)))
        );
        btn_settingLayout.setVerticalGroup(
            btn_settingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ind4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(btn_settingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btn_settingLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lbl11, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        sidePane.add(btn_setting, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 110, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pict/exit.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel11MousePressed(evt);
            }
        });
        sidePane.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        getContentPane().add(sidePane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 470));

        jPanel2.setBackground(new java.awt.Color(85, 170, 228));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_auto.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        txt_auto.setText("AUTO");
        jPanel2.add(txt_auto, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 142, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel3.setText("User:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 490, 30));

        cnthome.setBackground(new java.awt.Color(255, 255, 255));
        cnthome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setOpaque(false);

        jTable1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Jam", "Activity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setOpaque(false);
        jScrollPane1.setViewportView(jTable1);

        cnthome.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 400, 220));

        jScrollPane2.setOpaque(false);

        jTable2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id layanan", "nama layanan", "Harga"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setOpaque(false);
        jScrollPane2.setViewportView(jTable2);

        cnthome.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 400, 90));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("ACTIVITY");
        cnthome.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 160, -1, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("LAYANAN");
        cnthome.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 120, 30));

        getContentPane().add(cnthome, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 490, 440));

        setSize(new java.awt.Dimension(601, 470));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //arraylist  for layanan
    public ArrayList<paket> List1(){

        ArrayList<paket> List1 = new ArrayList<>();
        try
        {
           
            con = new koneksibos().setConnection();
            
            String query1= "select * from layanan ";               
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query1);
            paket conn;
            while(rs.next()){
                conn = new paket(rs.getString("id_service"),rs.getString("nama_service"),rs.getString("harga"));
                List1.add(conn);
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
            System.out.println("error");
        }
        return List1;
    }
    //show data grid
    public void showdata()
    {
        ArrayList<paket> list1 = List1();
        DefaultTableModel model = (DefaultTableModel)jTable2.getModel();
        model.setRowCount(0);
        
        Object[] row = new Object[3];
        for(int i = 0;i<list1.size();i++)
        {        
            row[0] = list1.get(i).callID();
            row[1] = list1.get(i).callnama();
            row[2] = list1.get(i).callharga();
            
            model.addRow(row);
        }
    
    }
    
    
    //arrraylist for aktifitas
    public ArrayList<aktifitas> List2(){
         
        ArrayList<aktifitas> List2 = new ArrayList<>();
        try
        {
            con = new koneksibos().setConnection();
            
            String query2= "select * from activity ";               
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query2);
            aktifitas conn;
            while(rs.next()){
                conn = new aktifitas(rs.getString("jam"),rs.getString("activity"));
                List2.add(conn);
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
            System.out.println("error");
        }
        return List2;
    }
    //show data grid
    public void showdata1()
    {
        ArrayList<aktifitas> list2 = List2();
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        model.setRowCount(0);
        
        Object[] row = new Object[2];
        for(int i = 0;i<list2.size();i++)
        {        
            row[0] = list2.get(i).calljam();
            row[1] = list2.get(i).callaksi();

            
            model.addRow(row);
        }
    
    }
    
    

    // aksesoris
    public void setcolor(JPanel pane)
    {
        pane.setBackground(new Color(32, 67, 102));
        
    }
    

    public void resetcolor(JPanel[] pane, JPanel [] indicators)
    {
        for (JPanel pane1 : pane) {
            pane1.setBackground(new Color(0, 40, 80));
        }
        for (JPanel indicator : indicators) {
            indicator.setOpaque(false);           
        }
        
    }
    
    private void btn_HomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_HomeMousePressed
        // TODO add your handling code here:
        setcolor(btn_Home);
        ind1.setOpaque(true);
        resetcolor(new JPanel[]{btn_anak,btn_transaksi,btn_setting}, new JPanel[]{ind2,ind3, ind4});
        
  
    }//GEN-LAST:event_btn_HomeMousePressed

    private void btn_anakMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_anakMousePressed
        // TODO add your handling code here:
        setcolor(btn_anak);
        ind2.setOpaque(true);
        resetcolor(new JPanel[]{btn_Home,btn_transaksi,btn_setting}, new JPanel[]{ind1,ind3, ind4});
        
        anakP x = new anakP();
        anakP.txt_auto.setText(MainParent.txt_auto.getText());
        x.setVisible(true);
        hide();
    //    hidecontent(new JPanel[] {cnthome});     
    }//GEN-LAST:event_btn_anakMousePressed

    private void btn_transaksiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_transaksiMousePressed
        // TODO add your handling code here:
        setcolor(btn_transaksi);
        ind3.setOpaque(true);
        resetcolor(new JPanel[]{btn_Home, btn_anak, btn_setting}, new JPanel[]{ind2,ind1, ind4});
        
        TrParent x = new TrParent();
        TrParent.txt_auto4.setText(MainParent.txt_auto.getText());
        x.setVisible(true);
        hide();
    }//GEN-LAST:event_btn_transaksiMousePressed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        setcolor(btn_Home);
        ind1.setOpaque(true);
        showdata();
        showdata1();
    }//GEN-LAST:event_formWindowActivated

    private void jLabel13MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel13MousePressed

    private void btn_settingMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_settingMousePressed
        // TODO add your handling code here:
        setcolor(btn_setting);
        ind4.setOpaque(true);
        resetcolor(new JPanel[]{btn_Home, btn_anak, btn_transaksi}, new JPanel[]{ind2,ind1, ind3});
    }//GEN-LAST:event_btn_settingMousePressed

    private void jLabel11MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MousePressed
        // TODO add your handling code here:
        logins pergi = new logins();
        pergi.show();
        hide();
    }//GEN-LAST:event_jLabel11MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainParent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainParent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainParent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainParent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainParent().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btn_Home;
    private javax.swing.JPanel btn_anak;
    private javax.swing.JPanel btn_setting;
    private javax.swing.JPanel btn_transaksi;
    private javax.swing.JPanel cnthome;
    private javax.swing.JPanel ind1;
    private javax.swing.JPanel ind2;
    private javax.swing.JPanel ind3;
    private javax.swing.JPanel ind4;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lbl10;
    private javax.swing.JLabel lbl11;
    private javax.swing.JLabel lbl8;
    private javax.swing.JLabel lbl9;
    private javax.swing.JPanel sidePane;
    public static javax.swing.JLabel txt_auto;
    // End of variables declaration//GEN-END:variables
}
