/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

/**
 *
 * @author KH
 */


import daycare.anak;
import daycare.koneksibos;
import daycare.parent2;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class regisEm extends javax.swing.JFrame {

    /**
     * Creates new form regisEm
     */
    
Statement st;
PreparedStatement pst;
Connection con;
ResultSet rs;
    public regisEm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    

    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        txtjenjang = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtjam = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        txhargaL = new javax.swing.JTextField();
        txtlayanan = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jTextField5 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(85, 170, 228));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pict/close1.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel10MousePressed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pict/browsers.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel11MousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel2.setText("REGISTRASI");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(198, 198, 198)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 323, Short.MAX_VALUE)
                .addComponent(jLabel10))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(21, 21, 21))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 70));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Tanggal registrasi");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, -1));

        lblID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblID.setText("AUTO");
        getContentPane().add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("No registrasi");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        jTextField4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextField4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextField4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField4MouseClicked(evt);
            }
        });
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 120, 190, 30));

        jDateChooser1.setDateFormatString("yyyy-MM-dd");
        jDateChooser1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jDateChooser1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jDateChooser1ComponentHidden(evt);
            }
        });
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 190, 30));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        txtjenjang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtjenjang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txtjenjang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtjenjangMousePressed(evt);
            }
        });
        txtjenjang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjenjangActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel22.setText("ID Jenjang");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("nama jenjang");

        txtjam.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtjam.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txtjam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtjamMousePressed(evt);
            }
        });
        txtjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjamActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel24.setText("Jam registrasi");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(96, 96, 96)
                        .addComponent(txtjenjang, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel24))
                        .addGap(77, 77, 77)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtjam, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(txtjam, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(txtjenjang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 410, 260));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setText("nama layanan");

        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jComboBox1MouseReleased(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setText("Harga layanan");

        txhargaL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txhargaL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txhargaL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txhargaLMousePressed(evt);
            }
        });
        txhargaL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txhargaLActionPerformed(evt);
            }
        });

        txtlayanan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtlayanan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txtlayanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtlayananMousePressed(evt);
            }
        });
        txtlayanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlayananActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setText("ID Layanan");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("LUNAS");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("BELUM LUNAS");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setText("Status");

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pict/tick.png"))); // NOI18N
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel21MousePressed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel23.setText("Simpan");

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pict/forbidden.png"))); // NOI18N
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel25MousePressed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel26.setText("batal");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(75, 75, 75)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(91, 91, 91)
                        .addComponent(txtlayanan, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel18))
                        .addGap(72, 72, 72)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton2)
                            .addComponent(txhargaL, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel26)
                                            .addComponent(jLabel25))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel23))
                                        .addGap(20, 20, 20))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(100, 100, 100)
                                        .addComponent(jRadioButton1)))))))
                .addGap(19, 19, 19))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(txtlayanan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(txhargaL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(jLabel25)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel26))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, 390, 260));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_orangtua", "Nama lengkap", "TTL", "jenis kelamin", "pekerjaan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 390, 110));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_anak", "Nama_lengkap", "TTL", "jenis kelamin", "id orang tua"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 410, 110));

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        jTextField5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextField5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField5KeyReleased(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("id_anak");

        jButton1.setText("Find");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(23, 23, 23))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(127, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 430, 170));

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("id orang tua");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jLabel14)
                .addContainerGap(208, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel14)
                .addContainerGap(132, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 410, 170));

        setBounds(300, 200, 899, 619);
    }// </editor-fold>//GEN-END:initComponents

    
    public void refresh()
    {
      jTextField4.setText(null);
      jTextField5.setText(null);
    }
    public void IdAuto()
    {
        try
        {
            con = new koneksibos().setConnection();
           
            String sql = "select no_registrasi FROM registrasi order by no_registrasi desc";
            
             st = con.createStatement();
             rs = st.executeQuery(sql);
            
            if(rs.next())
            {
                String ID = rs.getString("no_registrasi");
               
                
                String potong = ID.substring(1);
                int nextid = Integer.parseInt(potong)+1;
                if (nextid <= 10)
                {
                    ID = "R000" + nextid;
                }
                else if (nextid <= 100)
                {
                    ID = "R00" + nextid;
                }
                else if (nextid <= 1000)
                {
                    ID = "R0" + nextid;
                }
                 else if (nextid <= 10000)
                {
                    ID = "R" + nextid;
                }
                
                
                lblID.setText (ID);
            
            }
            else
            {
                lblID.setText("R0001");
            }
             
        }
        catch(NumberFormatException | SQLException e)
        {
         System.err.println("errror");
        }
    }
     
    public void combojenjang()
    {
        try {
             String sql = "Select * from jenjang";
             pst=con.prepareStatement(sql);
             rs=pst.executeQuery();
             while(rs.next())
             {
                 jComboBox2.addItem(rs.getString("Nama_jenjang"));
                 
             }         
         } 
         catch (SQLException e) {
         JOptionPane.showMessageDialog(this,e.getMessage());
             //   Logger.getLogger(schedule.class.getName()).log(Level.SEVERE, null, ex);
         }
    }
    
    public void combolayanan()
    {
        try 
        {
             String sql = "Select * from layanan";
             pst=con.prepareStatement(sql);
             rs=pst.executeQuery();
             while(rs.next())
             {
                 jComboBox1.addItem(rs.getString("nama_service"));
                 
             }         
         } 
         catch (SQLException e) {
         JOptionPane.showMessageDialog(this,e.getMessage());
             //   Logger.getLogger(schedule.class.getName()).log(Level.SEVERE, null, ex);
         }
    }
    
        public void Search2()
    {    
        try
            
        {
            con = new koneksibos().setConnection();
            String sql ="select * from jenjang where Nama_jenjang=?";   
            pst = con.prepareStatement(sql);
            pst.setString(1, jComboBox2.getSelectedItem().toString());
            
            rs = pst.executeQuery();
            if(rs.next())
            {
               // JOptionPane.showMessageDialog(this, " Data yang anda masukkan valid");
                String idjen= rs.getString("id_jenjang");
                txtjenjang.setText(idjen);
            }
            else
            {
                JOptionPane.showMessageDialog(this, " Data yang anda masukkan tidak valid");
            
            }
                    
        }
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
        
           
    }
    
      public void Search1()
    {    
        try
            
        {
            con = new koneksibos().setConnection();
            String sql ="select * from layanan where nama_service=?";   
            pst = con.prepareStatement(sql);
            pst.setString(1, jComboBox1.getSelectedItem().toString());
            
            rs = pst.executeQuery();
            if(rs.next())
            {
                //JOptionPane.showMessageDialog(this, " Data yang anda masukkan valid");
                String IDL= rs.getString("id_service");
                txtlayanan.setText(IDL);
                String satuan= rs.getString("harga");
                txhargaL.setText(satuan);
            }
            else
            {
                JOptionPane.showMessageDialog(this, " Data yang anda masukkan tidak valid");
            
            }
                    
        }
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    public void Search()
    {    
        try
            
        {
           con = new koneksibos().setConnection();
            String sql ="select * from anak where id_anak=?";   
            pst = con.prepareStatement(sql);
            pst.setString(1, jTextField5.getText());
            
            rs = pst.executeQuery();
            if(rs.next())
            {
                JOptionPane.showMessageDialog(this, " Data yang anda masukkan valid");
                String idortu= rs.getString("id_orangtua");
                jTextField4.setText(idortu);
            }
            else
            {
                JOptionPane.showMessageDialog(this, " Data yang anda masukkan tidak valid");
            
            }
                    
        }
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
        
           
    }
    
    public void add()
    {
        try
        {
            String status="";
            if (jRadioButton1.isSelected())
            {
                status = jRadioButton1.getText();
            }
            else if  (jRadioButton2.isSelected())
            {
              status = jRadioButton2.getText();
           
            }
            else
            {
                JOptionPane.showMessageDialog(this, " mungkin ada yang salah dengan data yang dipilih!");
            }
            
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String dates = sdf.format(jDateChooser1.getDate());
   
            con = new koneksibos().setConnection();         
            String sql="insert into dbo.registrasi (no_registrasi, tanggal_registrasi, jam_registrasi, id_orangtua, id_anak, id_jenjang, id_service, harga_layanan, statuss )" 
                    + "values(?,?,?,?,?,?,?,?,?)";
            
            pst = con.prepareStatement(sql);
            pst.setString(1, lblID.getText());
            pst.setString(2, dates);
            pst.setString(3, txtjam.getText());
            pst.setString(4, jTextField4.getText());
            pst.setString(5, jTextField5.getText());                    
            pst.setString(6, txtjenjang.getText());
            pst.setString(7, txtlayanan.getText());
            pst.setString(8, txhargaL.getText());
            pst.setString(9, status);
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, " Registration have been sucessfull, thank you !!!");
            refresh();
            IdAuto();
            
            MainPegawai dones = new MainPegawai();
            dones.show();
            hide();
            
        }
        catch(HeadlessException | SQLException e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    
    }
     
    
     public ArrayList<parent2> List2(String valtosearch)
    {
        ArrayList<parent2> List2 = new ArrayList<>();
        try
        {
            con = new koneksibos().setConnection();
            String query1= "select * from parent where CONCAT(nama_orangtua, id_orangtua)like '%" + valtosearch + "%' ";               
            st = con.createStatement();
            rs = st.executeQuery(query1);
            parent2 conn;
            while(rs.next()){
                conn = new parent2(rs.getString("id_orangtua"),rs.getString("nama_orangtua"),rs.getString("TTL"),rs.getString("jenis_kelamin"), rs.getString("pekerjaan"));
                List2.add(conn);
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
            System.out.println("error 1");
        }
        return List2;
    }
    
    public void showdata2()
    {
        ArrayList<parent2> list2 = List2(jTextField4.getText());
        
        DefaultTableModel model = new DefaultTableModel();
        //model.setRowCount(0);
       model.setColumnIdentifiers(new Object[]{"id orang tua","Nama_lengkap","TTL,","jenis kelamin", "pekerjaan"});
        Object[] row = new Object[5];
        for(int i = 0;i<list2.size();i++)
        {        
            row[0] = list2.get(i).callid();
            row[1] = list2.get(i).callnama();
            row[2] = list2.get(i).callttl();
            row[3] = list2.get(i).callJK();
            row[4] = list2.get(i).callPekerjaan();
            model.addRow(row);
        }
        jTable1.setModel(model);
        
    
    }
    
     public ArrayList<anak> List1(String valtosearch)
    {
        ArrayList<anak> List1 = new ArrayList<>();
        try
        {
           con = new koneksibos().setConnection();
            String query1= "select * from anak where CONCAT(Nama_lengkap, id_anak)like '%" + valtosearch + "%' ";               
            st = con.createStatement();
            rs = st.executeQuery(query1);
            anak conn;
            while(rs.next()){
                conn = new anak(rs.getString("id_anak"),rs.getString("Nama_lengkap"),rs.getString("TTL"),rs.getString("jenis_kelamin"), rs.getString("id_orangtua"));
                List1.add(conn);
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
            System.out.println("error");
        }
        return List1;
    }
    
    public void showdata1()
    {
        ArrayList<anak> list1 = List1(jTextField5.getText());
        
        DefaultTableModel model = new DefaultTableModel();
        //model.setRowCount(0);
        model.setColumnIdentifiers(new Object[]{"id_anak","Nama_lengkap","TTL,","jenis kelamin", "id orang tua"});
        Object[] row = new Object[5];
        for(int i = 0;i<list1.size();i++)
        {        
            row[0] = list1.get(i).callIDa();
            row[1] = list1.get(i).callnama();
            row[2] = list1.get(i).callTtl();
            row[3] = list1.get(i).calljenkel();
            row[4] = list1.get(i).callIDo();
            model.addRow(row);
        }
        jTable2.setModel(model);
        
    
    }
    
    private void jLabel10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MousePressed
        // TODO add your handling code here:
        MainPegawai back = new MainPegawai();
        back.show();
        hide();
    }//GEN-LAST:event_jLabel10MousePressed

    private void jLabel11MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel11MousePressed

    private void jLabel21MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MousePressed
        // TODO add your handling code here:
        add();
    }//GEN-LAST:event_jLabel21MousePressed

    private void jLabel25MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MousePressed
        // TODO add your handling code here:
        refresh();
    }//GEN-LAST:event_jLabel25MousePressed

    private void jDateChooser1ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jDateChooser1ComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_jDateChooser1ComponentHidden

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        IdAuto();
        combojenjang();
        combolayanan();
        jRadioButton2.setSelected(false);
        jRadioButton1.setSelected(true);
        
                
    }//GEN-LAST:event_formWindowActivated

    private void jTextField5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyReleased
        // TODO add your handling code here:
    
    }//GEN-LAST:event_jTextField5KeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Search();
        showdata1();
        showdata2();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
        // TODO add your handling code here:
       // 
    }//GEN-LAST:event_jComboBox1MouseClicked

    private void jComboBox1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseReleased
        // TODO add your handling code here:
        //
    }//GEN-LAST:event_jComboBox1MouseReleased

    private void txhargaLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txhargaLActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txhargaLActionPerformed

    private void txhargaLMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txhargaLMousePressed
        // TODO add your handling code here:
      //  Search1();
    }//GEN-LAST:event_txhargaLMousePressed

    private void txtlayananMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtlayananMousePressed
        // TODO add your handling code here:
        Search1();
    }//GEN-LAST:event_txtlayananMousePressed

    private void txtlayananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlayananActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlayananActionPerformed

    private void txtjenjangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtjenjangMousePressed
        // TODO add your handling code here:
        Search2();
    }//GEN-LAST:event_txtjenjangMousePressed

    private void txtjenjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjenjangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjenjangActionPerformed

    private void txtjamMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtjamMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjamMousePressed

    private void txtjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjamActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField4MouseClicked
        // TODO add your handling code here:
         
    }//GEN-LAST:event_jTextField4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(regisEm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(regisEm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(regisEm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(regisEm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new regisEm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JLabel lblID;
    private javax.swing.JTextField txhargaL;
    private javax.swing.JTextField txtjam;
    private javax.swing.JTextField txtjenjang;
    private javax.swing.JTextField txtlayanan;
    // End of variables declaration//GEN-END:variables
}
